### ISSUE TITLE
Anyrun panics when added via flake

### ISSUE THREAD

**Issue by Sntx626** [Kirottu/anyrun#68]
I've added anyrun to my system config as described in the readme
(c.f. [commit](https://git.sr.ht/~sntx/flake/commit/5f82711356fb63747c55f0bafd40c0d45d8d530f)).

I get the Error:
```
Failed to load custom CSS: <broken file>:1:0Failed to import: Error opening file /etc/anyrun/style.css: No such file or directory
thread 'main' panicked at 'Invalid plugin path', anyrun/src/main.rs:346:22
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::option::expect_failed
   3: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   4: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   5: anyrun::activate
   6: <O as gio::auto::application::ApplicationExt>::connect_activate::activate_trampoline
   7: g_closure_invoke
   8: signal_emit_unlocked_R.isra.0
   9: g_signal_emit_valist
  10: g_signal_emit
  11: g_application_real_local_command_line
  12: g_application_run
  13: <O as gio::application::ApplicationExtManual>::run_with_args
  14: anyrun::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Kirottu** [comment]
Well, it is clear that at least some path to a plugin is wrong in the config file, don't use Nix myself so I don't really know how to resolve this.

Your time to shine @NotAShelf @n3oney

**Comment by NotAShelf** [comment]
How are you adding the plugin? Could you share your configuration?

**Comment by Sntx626** [comment]
The relevant part of the configuration is linked in the commit in my original post.
The configuration i produced that error with is available here:
https://git.sr.ht/~sntx/flake/tree/anyrun

**Comment by n3oney** [comment]
try using the HM module

**Comment by NotAShelf** [comment]
I see virtually nothing wrong with the configuration that you have linked, and I'm unable to reproduce with the anyrun package added through environment.systemPackages

**Comment by Sntx626** [comment]
I just setup a new machine, though trying to setup anyrun with the config reproduces the same error.

```sh
ヌ anyrun
Failed to load custom CSS: <broken file>:1:0Failed to import: Error opening file /etc/anyrun/style.css: No such file or directory
thread 'main' panicked at 'Invalid plugin path', anyrun/src/main.rs:389:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
ヌ sudo mkdir /etc/anyrun
ヌ sudo touch /etc/anyrun/style.css
ヌ anyrun
thread 'main' panicked at 'Invalid plugin path', anyrun/src/main.rs:389:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Sntx626** [comment]
I get a build error with the HM module, but since I can't really rule out my config as the cause for this one, I opened the issue with a minimal example (which should not rely on my config).

This is the error when building with the HM module:
```sh
ヌ sudo nixos-rebuild switch --flake .
error:
       … while calling the 'seq' builtin

         at /nix/store/nhk2gnp8jf1xshlym3g63m6k7v35p21h-source/lib/modules.nix:320:18:

          319|         options = checked options;
          320|         config = checked (removeAttrs config [ "_module" ]);
             |                  ^
          321|         _module = checked (config._module);

       … while calling the 'throw' builtin

         at /nix/store/nhk2gnp8jf1xshlym3g63m6k7v35p21h-source/lib/modules.nix:296:18:

          295|                     ''
          296|             else throw baseMsg
             |                  ^
          297|         else null;

       error: The option `xdg.configFile' does not exist. Definition values:
       - In `/nix/store/jnv33m5dpb0m8mcn9jn6xysdl21zvs7r-source/modules/programs/anyrun':
           {
             _type = "if";
             condition = false;
             content = {
               _type = "merge";
           ...
```

This is the module I use:
```nix
{ config, lib, inputs, pkgs, ... }:

with lib;
let cfg = config.myPrograms.anyrun;

in {
  imports = [ inputs.anyrun.homeManagerModules.default ];

  options.myPrograms.anyrun = {
    enable = mkOption {
      type = types.bool;
      default = false;
    };
  };

  config = mkIf cfg.enable {
    home.programs.anyrun = {
      enable = true;
      config = {
        plugins = [ inputs.anyrun.packages.${pkgs.system}.applications ];
      };
    };
  };
}
```

Interestingly enough, I get the same Error, even when I remove the whole `config` attribute from my module and just import the anyrun HM module.
I've also tried importing `inputs.anyrun.nixosModules.home-manager`, expectedly it didn't change anything.
C.f.:
```nix
{ lib, inputs, ... }:

with lib;

{
  imports = [
    # inputs.anyrun.homeManagerModules.default
    inputs.anyrun.nixosModules.home-manager
  ];

  options.myPrograms.anyrun = {
    enable = mkOption {
      type = types.bool;
      default = false;
    };
  };
}
```

PS:

Why do I think my config might be the culprit with this error?
I link to attributes of HM, so that I can use it easily together with my system config.
However I still don't understand why the import fails.

This is set elsewhere in my config (/modules/options.nix):
```nix
{ config, options, lib, ... }:

with lib;

{
  options = {
    user = mkOption { };

    home = {
      dconf = mkOption { };
      file = mkOption { description = "Files to place in $HOME"; };
      packages = mkOption { description = "User-level installed packages"; };
      programs = mkOption { description = "Programs managed directly from home-manager"; };
      services = mkOption { description = "Services managed directly from home-manager"; };
      sessionVariables = mkOption { };

      xdg = mkOption { description = "Management of XDG base directories."; };
    };
  };

  config = {
    users.users.${config.user.name} = mkAliasDefinitions options.user;

    home-manager = {
      useGlobalPkgs = true;
      useUserPackages = true;

      users.${config.user.name} = {
        home = {
          stateVersion = config.system.stateVersion;
        };

        dconf = mkAliasDefinitions options.home.dconf;
        home.file = mkAliasDefinitions options.home.file;
        home.packages = mkAliasDefinitions options.home.packages;
        programs = mkAliasDefinitions options.home.programs;
        services = mkAliasDefinitions options.home.services;
        home.sessionVariables = mkAliasDefinitions options.home.sessionVariables;

        xdg = mkAliasDefinitions options.home.xdg;
      };
    };
  };
}
```

**Comment by teto** [comment]
I've just launched `nix run 'github:Kirottu/anyrun'` which is I feel a great way to let users test the application but I see the same error
```
$ nix run 'github:Kirottu/anyrun'
Failed to load custom CSS: <broken file>:1:0Failed to import: Error opening file /etc/anyrun/style.css: No such file or directory
```
There could be a default CSS embedded in binary or fallbacks.

**Comment by NotAShelf** [comment]
A solution could be to provide two packages: wrapped and unwrapped. Wrapped is shipped with default configurations where unwrapped is just the binary. By setting wrapped as packages.default, we can get around the nix run issue, and the home-manager module would use the unwrapped package.

**Comment by n3oney** [comment]
do it then and also make sure to set meta.mainProgram

**Comment by n3oney** [comment]
> A solution could be to provide two packages: wrapped and unwrapped. Wrapped is shipped with default configurations where unwrapped is just the binary. By setting wrapped as packages.default, we can get around the nix run issue, and the home-manager module would use the unwrapped package.

this collides with the anyrun and anyrun-with-all-plugins approach i guess?

**Comment by NotAShelf** [comment]
> > A solution could be to provide two packages: wrapped and unwrapped. Wrapped is shipped with default configurations where unwrapped is just the binary. By setting wrapped as packages.default, we can get around the nix run issue, and the home-manager module would use the unwrapped package.
> 
> this collides with the anyrun and anyrun-with-all-plugins approach i guess?

what about anyrun-wrapped and anyrun-wrapped-with-plugins?

unwrapped is, well, unwrapped. user is supposed to bring their own plugins if choosing to use the unwrapped package

**Comment by Sntx626** [comment]
This issue is fixed.

`nix run github:Kirottu/anyrun#anyrun-with-all-plugins` runs anyrun just fine.

Thanks

**Comment by teto** [comment]
might be offtopic but  I tried to type `:def computer` to get the definition of "computer" but nothing happens. Same when searching `?braam moolenar` which should open google in browser IIUC ? 

All plugins are there it seems:
``` 
nix build github:Kirottu/anyrun#anyrun-with-all-plugins          
➜ ls result/lib/lib
file
libapplications.so*  libkidex.so*         librink.so*          libstdin.so*         libtranslate.so*                                                                                 
libdictionary.so*    librandr.so*         libshell.so*         libsymbols.so*       libwebsearch.so* 
```

NB: I tried to launch with --y 200 to change the window position but the program crashes. I tried relative number as well : `--y 0.4` with the same result.Can we have an example in --help ?

**Comment by Sntx626** [comment]
`:def computer` and `?braam moolenar` both works for me.

Can reproduce the crash when launching with `--y 200` and `--y 0.4`.

**Comment by Kirottu** [comment]
The position and size parameters are set with values of `absolute:<value>` or `fraction:<value>`.

**Comment by Sntx626** [comment]
> The position and size parameters are set with values of `absolute:<value>` or `fraction:<value>`.

This works!

We should open an issue and add documentation on it like @teto said.
